import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { globSync } from "node:fs";
import writeFileAtomic from "write-file-atomic";
import { isMainModule } from "@breaker/kit";

const __dirname = dirname(fileURLToPath(import.meta.url));
const strategiesDir = join(__dirname, "../strategies");

/**
 * Scan all deployed strategy files and generate the top-level barrel.
 * Writes to `src/strategies/deployed/index.ts`.
 */
export function generateDeployedBarrel(rootDir?: string): string[] {
  const root = rootDir ?? strategiesDir;
  const barrelDir = join(root, "deployed");
  const barrelPath = join(barrelDir, "index.ts");

  // Glob all .ts files inside {asset}/{category}/deployed/, excluding index.ts
  const pattern = join(root, "*/*/deployed/*.ts");
  const files = globSync(pattern).filter(
    (f) => !f.endsWith("/index.ts"),
  );
  files.sort();

  if (files.length === 0) {
    writeFileAtomic.sync(
      barrelPath,
      "// Auto-generated — no deployed strategies found\nexport {};\n",
    );
    return [];
  }

  const lines = files.map((f) => {
    const rel = relative(barrelDir, f).replace(/\.ts$/, ".js");
    return `export * from "./${rel}";`;
  });

  const content = [
    "// Auto-generated by generate-deployed-barrel.ts — do not edit manually",
    ...lines,
    "",
  ].join("\n");

  writeFileAtomic.sync(barrelPath, content);
  return files;
}

if (isMainModule(import.meta.url)) {
  const files = generateDeployedBarrel();
  if (files.length === 0) {
    console.log("No deployed strategies found. Wrote empty barrel.");
  } else {
    console.log(`Generated barrel with ${files.length} strategy(ies):`);
    for (const f of files) {
      console.log(`  ${f}`);
    }
  }
}
