import { join, dirname, relative, basename, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { globSync, readFileSync } from "node:fs";
import writeFileAtomic from "write-file-atomic";
import { isMainModule } from "@breaker/kit";

const __dirname = dirname(fileURLToPath(import.meta.url));
const strategiesDir = join(__dirname, "../strategies");

export interface DeployedStrategyEntry {
  factoryName: string;
  strategyName: string;
  coin: string;
  interval: string;
  moduleType: string;
}

/**
 * Extract metadata from a deployed strategy file.
 *
 * - `coin` and `moduleType` are derived from the directory structure:
 *   `{asset}/{category}/deployed/{name}.ts`
 * - `interval` is parsed from the strategy's `name:` field which follows
 *   the convention `{ASSET} {TF} {Category} — {Strategy Name}`
 * - `factoryName` is the exported `create*` function name
 */
function extractMetadata(filePath: string, rootDir: string): DeployedStrategyEntry | null {
  const source = readFileSync(filePath, "utf-8");

  // Factory name: `export function createFoo(`
  const factoryMatch = source.match(/export\s+function\s+(create\w+)/);
  if (!factoryMatch) return null;

  // Strategy display name: `name: "BTC 4H Trend Following — ..."`
  const nameMatch = source.match(/name:\s*["'`]([^"'`]+)["'`]/);
  if (!nameMatch) return null;

  // Parse interval from display name (second token)
  const nameParts = nameMatch[1].split(/\s+/);
  if (nameParts.length < 3) return null;
  const interval = nameParts[1].toLowerCase();

  // Derive coin and moduleType from path: {root}/{asset}/{category}/deployed/{file}.ts
  const relPath = relative(rootDir, filePath);
  const segments = relPath.split(sep);
  // segments = ["btc", "trend-following", "deployed", "macd-htf-adx-high-chandelier.ts"]
  if (segments.length < 4) return null;
  const coin = segments[0].toUpperCase();
  const moduleType = segments[1];

  const strategyName = basename(filePath, ".ts");

  return {
    factoryName: factoryMatch[1],
    strategyName,
    coin,
    interval,
    moduleType,
  };
}

/**
 * Scan all deployed strategy files and generate the top-level barrel
 * with factory re-exports and a `deployedManifest` for auto-discovery.
 * Writes to `src/strategies/deployed/index.ts`.
 */
export function generateDeployedBarrel(rootDir?: string): string[] {
  const root = rootDir ?? strategiesDir;
  const barrelDir = join(root, "deployed");
  const barrelPath = join(barrelDir, "index.ts");

  // Glob all .ts files inside {asset}/{category}/deployed/, excluding index.ts
  const pattern = join(root, "*/*/deployed/*.ts");
  const files = globSync(pattern).filter(
    (f) => !f.endsWith("/index.ts"),
  );
  files.sort();

  if (files.length === 0) {
    writeFileAtomic.sync(
      barrelPath,
      "// Auto-generated — no deployed strategies found\nexport {};\nexport const deployedManifest: DeployedStrategyEntry[] = [];\nexport interface DeployedStrategyEntry { factoryName: string; strategyName: string; coin: string; interval: string; moduleType: string; }\n",
    );
    return [];
  }

  // Re-export lines
  const exportLines = files.map((f) => {
    const rel = relative(barrelDir, f).replace(/\.ts$/, ".js");
    return `export * from "./${rel}";`;
  });

  // Extract metadata for manifest
  const entries: DeployedStrategyEntry[] = [];
  for (const f of files) {
    const meta = extractMetadata(f, root);
    if (meta) {
      entries.push(meta);
    } else {
      console.warn(`  WARNING: Could not extract metadata from ${basename(f)} — skipping manifest entry`);
    }
  }

  // Generate manifest lines
  const manifestLines = entries.map((e) =>
    `  { factoryName: "${e.factoryName}", strategyName: "${e.strategyName}", coin: "${e.coin}", interval: "${e.interval}", moduleType: "${e.moduleType}" },`,
  );

  const content = [
    "// Auto-generated by generate-deployed-barrel.ts — do not edit manually",
    ...exportLines,
    "",
    "export interface DeployedStrategyEntry {",
    "  factoryName: string;",
    "  strategyName: string;",
    "  coin: string;",
    "  interval: string;",
    "  moduleType: string;",
    "}",
    "",
    "export const deployedManifest: DeployedStrategyEntry[] = [",
    ...manifestLines,
    "];",
    "",
  ].join("\n");

  writeFileAtomic.sync(barrelPath, content);
  return files;
}

if (isMainModule(import.meta.url)) {
  const files = generateDeployedBarrel();
  if (files.length === 0) {
    console.log("No deployed strategies found. Wrote empty barrel.");
  } else {
    console.log(`Generated barrel with ${files.length} strategy(ies):`);
    for (const f of files) {
      console.log(`  ${f}`);
    }
  }
}
